-- ==================================================
-- MAGNITUDE analysis
-- ==================================================
-- Find total customers by countries
select country,
count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers DESC

-- Find total customers by gender
select gender, 
count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers DESC

-- Find total products by category
select category, 
count(product_key) as total_products
from gold.dim_products
group by category
order by total_products DESC

-- What is the avg costs in each category
select category, 
AVG(cost) as avg_costs
from gold.dim_products
group by category
order by avg_costs DESC

-- What is the total revenue generated for each category
select
p.category,
SUM(f.sales_amount) total_revenue
from gold.fact_sales f 
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Find the total revenue generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

-- What is distribution  of sold items across countries
select
c.country,
SUM(f.quantity) as total_sold_items
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC
